name: Deploy to External GitHub Pages Repo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      domain:
        description: 'Dominio personalizado (dejar vacío para usar GitHub Pages)'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Asegurar que todos los archivos se descarguen

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2

      - name: Verify file structure
        run: |
          echo "Verificando estructura de archivos..."
          ls -la
          echo "Contenido del directorio data:"
          ls -la data/
          echo "Contenido del directorio templates:"
          ls -la templates/
          echo "Contenido del directorio static:"
          ls -la static/

      - name: Set BASE_URL for GitHub Pages
        if: github.event.inputs.domain == ''
        run: |
          echo "BASE_URL=https://p4blo4p.github.io/hoteles-booking-web-pages" >> $GITHUB_ENV

      - name: Set BASE_URL for custom domain
        if: github.event.inputs.domain != ''
        run: |
          echo "BASE_URL=${{ github.event.inputs.domain }}" >> $GITHUB_ENV

      - name: Generate site
        env:
          BASE_URL: ${{ env.BASE_URL }}
        run: |
          echo "Usando BASE_URL: $BASE_URL"
          python scripts/generate.py  # ← CORREGIDO AQUÍ

      - name: Verify generated files
        run: |
          echo "Verificando archivos generados..."
          ls -la
          echo "Contenido del directorio hotel:"
          ls -la hotel/

      - name: Copy all files to a temp directory
        run: |
          mkdir deploy
          cp -r index.html hotel static deploy/
          echo "Archivos copiados:"
          ls -la deploy/

      - name: Push to GitHub Pages Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./deploy
          external_repository: p4blo4p/hoteles-booking-web-pages
          publish_branch: gh-pages
          force_orphan: true