name: Deploy static to GitHub Pages repo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Copy static files to a temp directory
        run: |
          mkdir deploy
          cp -r static/* deploy/

      - name: Push to GitHub Pages Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./deploy
          external_repository: p4blo4p/hoteles-booking-web-pages
          publish_branch: gh-pages
          force_orphan: true # Borra el historial previo de la rama destino (opcional)
